import colorama 
from colorama import *
import time 
time.sleep(4)
print(Fore.RED+Sys.BRIGHT+"CODED BY SHAIK AFRID :)")
time.sleep(4)
a="fb login"
b="fake login"
c="fake password"
print(time.sleep(6)+Fore.YELLOW+Sys.BRIGHT+"SELECT WHAT U WANT")
time.sleep(2)
print(a)
time.sleep(2)
print(b)
time.sleep(2)
print(c)
x=input("INPUT WHAT U WANT:-")
time.sleep(4)
print("PLESE WAIT...../")
time.sleep(2)
if x==a :
       d=input(Fore.REd+Sys.BRIGHT+"ENTER UR FACEBOOK ID:-")
       e=nput(Fore.REd+Sys.BRIGHT+"ENTER FACEBOOK PASSWORD:-")
       print(Fore.yellOW+"SELECTED SUCESSFULLY:)")
       

       
if x==b:
       time.sleep(3)
       
       print("SORRY THIS IS STILL WORKING:(")
       print("SELECT ANOTHER OPTION:)")
             
             


       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       








