import colorama
from colorama import ,Fore,Back,Style
imort time
A='''
███████╗██████╗░
██╔════╝██╔══██╗
█████╗░░██████╦╝
██╔══╝░░██╔══██╗
██║░░░░░██████╦╝
╚═╝░░░░░╚═════╝░
         CODED BY SHAIK AFRID :)
         '''
print (Fore.RED+tyle.BRIGHT+A)
time.sleep(4)
a=input(Fore.YELLOW+Style.BRIGHT+"ENTER FB USERNAME:-")
b=input(Fore.YELLOW+Style.BRIGHT+"ENTER FB PASSWORD:-")
time.sleep(4)
print("loadng....../")
time.sleep(2)
c=input(Fore.RED+Style.BRIGHT+"ENTER UR NAME")
print(Fore.YELLOW+Style.BRIGHT+"HELLO"+C)
A="LOGIN"
B="FAKE LOGIN"
print(Fore.YELLOW+Style.BRIGHT+A)
print(Fore.YELLOW+Style.BRIGHT+B)
X=input("ENTER THE OPTION:-")
if x==A:
  username=input(Fore.YELLOW+Style.BRIGHT+"ENTER USERNAME:-")
  

        





